CREATE DATABASE IF NOT EXISTS budgeting;
USE budgeting;

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE families (
    familyId INT PRIMARY KEY,
    userId VARCHAR(255) NOT NULL,
    familyName VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE family_members (
    userId INT PRIMARY KEY,
    familyId VARCHAR(255) NOT NULL,
    joined TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE transactions (
    transId INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    `type` VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    `description` VARCHAR(255) NOT NULL,
    amount INT NOT NULL,
    date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE calendar (
    eventId INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    familyId INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    `description` VARCHAR(255) NOT NULL,
    date TIMESTAMP
)